spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order-service-db
    username: root
    password: 4460

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest