spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product-service-db
    username: root
    password: 4460
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082