spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service-db
    username: root
    password: 4460
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8084

jwt:
  secret: aioshdiuasdgh89ajkhsjdohasohdhaoshdfjolsjdf